Here I created a monad for handle errors inside Typescript. Two things happens,
that are weird.

First, the error structure and the monad itself holds preatty well in the same
module. Second, ther is no need for "wrapper", as Alex(2021) stated a wraper is.

So Â¿how can I tell if this is actually a monad?

Studying With Alex. The Absolute Best Intro to Monads For Software Engineers,
2021. https://www.youtube.com/watch?v=C2w45qRc3aU.
